package puntoventa;

import Conexion.Conexion;
import java.sql.Connection;
import java.time.LocalDate;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class NuevaVenta extends javax.swing.JFrame {

    /**
     * Creates new form NuevaVenta
     */
    public NuevaVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtNSucursal.setModel(GetValues());
        txtNProducto.setModel(GetValuesProductos());
    }

    private void cargarTablaNuevaVenta(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tbNuevaVenta.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int folio = Integer.parseInt(txtNFolioVenta.getText());
        int columnas;
        int[] anchos={70,70,100,100,100};
        for (int i=0;i<tbNuevaVenta.getColumnCount();i++){
            tbNuevaVenta.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try{
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT folioVenta_id, producto_id, precio, cantidad, importe FROM detalleVenta WHERE folioVenta_id=?");
            ps.setInt(1, folio);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while (rs.next()){
                Object[] fila = new Object[columnas];
                for (int i = 0; i<columnas; i++){
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void agregarVenta(){
        LocalDate todaysDate = LocalDate.now();
        int sucursalid = Integer.parseInt((txtNSucursal.getSelectedItem().toString()));
        String fecha = todaysDate.toString();
        
        try{
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareCall("{call Insertar_Venta(?,?)}");
            ps.setInt(1, sucursalid);
            ps.setString(2, fecha);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro de venta generado");
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Registro de venta no generado por el siguiente motivo");
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void agregar(){
       try{
            String nombre=(txtNProducto.getSelectedItem().toString());
            ResultSet rs;
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("SELECT id,precio FROM Producto WHERE nombre=?");
            ps.setString(1, nombre);
            rs = ps.executeQuery();
            while(rs.next()){
                txtNPrecio.setText(rs.getString("precio"));
                txtNProd.setText(rs.getString("id"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        } 
    }
    
    private void sumaSubtotal(){
        try{
            int folio = Integer.parseInt(txtNFolioVenta.getText());
            ResultSet rs;
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareCall("SELECT SUM(importe) AS importe FROM detalleVenta WHERE folioVenta_id=?");
            ps.setInt(1, folio);
            rs = ps.executeQuery();
            while (rs.next()){
                txtNSubtotal.setText(rs.getString("importe"));
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNuevaVenta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNFolioVenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNPrecio = new javax.swing.JTextField();
        btnNAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNSubtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNIVA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNTotal = new javax.swing.JTextField();
        btnNCompletarVenta = new javax.swing.JButton();
        btnNLimpiar = new javax.swing.JButton();
        btnNCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNSucursal = new javax.swing.JComboBox<>();
        txtNProducto = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        CargarPrecio = new javax.swing.JButton();
        txtNProd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 203, 219));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NuevaVenta");

        tbNuevaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "folioVenta_id", "producto_id", "precio", "cantidad", "importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbNuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNuevaVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNuevaVenta);
        if (tbNuevaVenta.getColumnModel().getColumnCount() > 0) {
            tbNuevaVenta.getColumnModel().getColumn(0).setResizable(false);
            tbNuevaVenta.getColumnModel().getColumn(1).setResizable(false);
            tbNuevaVenta.getColumnModel().getColumn(2).setResizable(false);
            tbNuevaVenta.getColumnModel().getColumn(3).setResizable(false);
            tbNuevaVenta.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("folioVenta");

        txtNFolioVenta.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("sucursal_id");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("producto");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("cantidad");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Detalles del producto");

        txtNPrecio.setEditable(false);
        txtNPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNPrecioActionPerformed(evt);
            }
        });

        btnNAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnNAgregar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNAgregar.setText("Agregar");
        btnNAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNAgregarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("subtotal");

        txtNSubtotal.setEditable(false);
        txtNSubtotal.setText("0");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("IVA");

        txtNIVA.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("total");

        txtNTotal.setEditable(false);

        btnNCompletarVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnNCompletarVenta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNCompletarVenta.setText("Completar venta");
        btnNCompletarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCompletarVentaActionPerformed(evt);
            }
        });

        btnNLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnNLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNLimpiar.setText("Limpiar");
        btnNLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNLimpiarActionPerformed(evt);
            }
        });

        btnNCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnNCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNCancelar.setText("Cancelar Venta");
        btnNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCancelarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Generar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNSucursal.setModel(txtNSucursal.getModel());
        txtNSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNSucursalActionPerformed(evt);
            }
        });

        txtNProducto.setEditable(true);
        txtNProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNProductoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CargarPrecio.setBackground(new java.awt.Color(255, 255, 255));
        CargarPrecio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CargarPrecio.setText("...");
        CargarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarPrecioActionPerformed(evt);
            }
        });

        txtNProd.setEditable(false);
        txtNProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(779, 779, 779)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNSubtotal)
                                            .addComponent(txtNIVA)
                                            .addComponent(txtNTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNFolioVenta)
                                            .addComponent(txtNSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7)
                                    .addComponent(txtNProd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(txtNCantidad)
                                    .addComponent(txtNPrecio)
                                    .addComponent(btnNCompletarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnNAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(CargarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNFolioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtNProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CargarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(btnNCompletarVenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnNCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCancelarActionPerformed
        int folio = Integer.parseInt(txtNFolioVenta.getText());
        
        try{
        Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("Delete from Venta WHERE folioVenta=?");            
            ps.setInt(1, folio);
            ps.execute();
            
            this.dispose();
            Sistema sis = new Sistema();
            sis.setVisible(true);
            JOptionPane.showMessageDialog(null, "Venta Cancelada");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnNCancelarActionPerformed

    private void btnNAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNAgregarActionPerformed
        cargarTablaNuevaVenta();
        int folio = Integer.parseInt(txtNFolioVenta.getText());
        int productoid = Integer.parseInt(txtNProd.getText());
        int cantidad = Integer.parseInt(txtNCantidad.getText());
        agregar();
        
        double precio = Double.parseDouble(txtNPrecio.getText());
        try{
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO detalleVenta VALUES (?,?,?,?,?)");
            ps.setInt(1, folio);
            ps.setInt(2, productoid);
            ps.setDouble(3, precio);
            ps.setInt(4, cantidad);
            ps.setDouble(5, (precio*cantidad));
            ps.executeUpdate();
            txtNPrecio.setText("");
            txtNCantidad.setText("");
            cargarTablaNuevaVenta();
            sumaSubtotal();
            double subtotal= Double.parseDouble(txtNSubtotal.getText());
            double iva = subtotal * 0.16;
            double total = subtotal + iva;
            txtNIVA.setText(Double.toString(iva));
            txtNTotal.setText(Double.toString(total));
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnNAgregarActionPerformed

    private void btnNCompletarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCompletarVentaActionPerformed
        int folio = Integer.parseInt(txtNFolioVenta.getText());
        double subtotal = Double.parseDouble(txtNSubtotal.getText());
        double iva = Double.parseDouble(txtNIVA.getText());
        double total = Double.parseDouble(txtNTotal.getText());
        
        try{
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Venta SET subtotal=?, iva=?, total=? WHERE folioVenta=?");
            ps.setDouble(1, subtotal);
            ps.setDouble(2, iva);
            ps.setDouble(3, total);
            ps.setInt(4, folio);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Venta realizada");
            txtNFolioVenta.setText("");
            txtNSubtotal.setText("");
            txtNIVA.setText("");
            txtNTotal.setText("");
            txtNPrecio.setText("");
            txtNCantidad.setText("");
            this.dispose();
            Sistema sis = new Sistema();
            sis.setVisible(true);
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnNCompletarVentaActionPerformed

    private void btnNLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNLimpiarActionPerformed

        txtNPrecio.setText("");
        txtNCantidad.setText("");
        txtNProd.setText("");
    }//GEN-LAST:event_btnNLimpiarActionPerformed

    private void tbNuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNuevaVentaMouseClicked
        try{
        int fila =tbNuevaVenta.getSelectedRow();
        int id=Integer.parseInt(tbNuevaVenta.getValueAt(fila, 0).toString());
        PreparedStatement ps;
        ResultSet rs;
        
        Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT producto_id, precio, cantidad, importe FROM detalleVenta WHERE folioVenta_id=?");
            ps.setInt(1, id);
            rs = ps.executeQuery();            
           
            while(rs.next()){
                txtNPrecio.setText(rs.getString("precio"));
                txtNCantidad.setText(rs.getString("cantidad"));
            }
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
    }
    }//GEN-LAST:event_tbNuevaVentaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarVenta();
        try{
        PreparedStatement ps;
        ResultSet rs;
        
        Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT TOP 1 folioVenta FROM Venta ORDER BY folioVenta DESC");
            rs = ps.executeQuery();            
           
            while(rs.next()){
                txtNFolioVenta.setText(rs.getString("folioVenta"));
            }
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
    }
                                      
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void txtNSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNSucursalActionPerformed

    }//GEN-LAST:event_txtNSucursalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
            Sistema sis = new Sistema();
            sis.setVisible(true);
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNPrecioActionPerformed

    private void txtNProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNProductoActionPerformed

    private void CargarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPrecioActionPerformed
        agregar();
    }//GEN-LAST:event_CargarPrecioActionPerformed

    private void txtNProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNProdActionPerformed

    //Esta clase importa los valores a la lista desplegable
    private DefaultComboBoxModel GetValues(){
       DefaultComboBoxModel modelo=new DefaultComboBoxModel();
       try{
        ResultSet rs;       
        Connection con = Conexion.getConexion(); 
        String sql ="select id from Sucursal";
        Statement st=con.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){
            modelo.addElement(rs.getString(1));
        }
        
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
        }
       return modelo;
    }
    
    private DefaultComboBoxModel GetValuesProductos(){
       DefaultComboBoxModel modelo=new DefaultComboBoxModel();
       try{
        ResultSet rs;       
        Connection con = Conexion.getConexion(); 
        String sql ="select id,nombre,precio from Producto";
        Statement st=con.createStatement();
        rs=st.executeQuery(sql);
        while(rs.next()){
            modelo.addElement(rs.getString(2));
        }
        
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
        }
       return modelo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarPrecio;
    private javax.swing.JButton btnNAgregar;
    private javax.swing.JButton btnNCancelar;
    private javax.swing.JButton btnNCompletarVenta;
    private javax.swing.JButton btnNLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNuevaVenta;
    private javax.swing.JTextField txtNCantidad;
    private javax.swing.JTextField txtNFolioVenta;
    private javax.swing.JTextField txtNIVA;
    private javax.swing.JTextField txtNPrecio;
    private javax.swing.JTextField txtNProd;
    private javax.swing.JComboBox<String> txtNProducto;
    private javax.swing.JTextField txtNSubtotal;
    private javax.swing.JComboBox<String> txtNSucursal;
    private javax.swing.JTextField txtNTotal;
    // End of variables declaration//GEN-END:variables
}
